repos:
  - repo: https://github.com/JakobKlotz/md-snakeoil
    rev: v0.1.7
    hooks:
      - id: snakeoil

  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0  # Use the ref you want to point at
    hooks:
    - id: mdformat
      additional_dependencies:
        - mdformat-mkdocs
      args: [--wrap, "79"]
          