# taken from https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions
# and adapted
name: ci
on:
  workflow_dispatch:  # Enable manual trigger
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - .gitignore
      - .dockerignore
      - docker-compose.yaml
      - Dockerfile

concurrency:
  group: pages-deployment
  cancel-in-progress: false  # Wait for previous deployments to finish

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the whole git history
          # (needed for git-revision-date-localized & 
          # mkdocs-git-authors-plugin plugin)

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      
      # respects pinned Python version
      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked

      - name: Build the site and deploy
        run: uv run mkdocs gh-deploy --force